[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ecom = "9D31LUnoNS7th12sKKZ1M8sYrhUbXaRK5RYQZ9D6tads"

[programs.testnet]
ecom = "9D31LUnoNS7th12sKKZ1M8sYrhUbXaRK5RYQZ9D6tads"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/home/ashar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
